version: "3.9"
services:
  processo1:
    build: .
    command: ["python", "main_udp.py", "1", "6001"]
    ports:
      - "6001:6001"
    networks:
      bully_net:
        ipv4_address: 172.28.0.2

  processo2:
    build: .
    command: ["python", "main_udp.py", "2", "6002"]
    ports:
      - "6002:6002"
    networks:
      bully_net:
        ipv4_address: 172.28.0.3

  processo3:
    build: .
    command: ["python", "main_udp.py", "3", "6003"]
    ports:
      - "6003:6003"
    networks:
      bully_net:
        ipv4_address: 172.28.0.4

networks:
  bully_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
